import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased border bg-background h-screen flex flex-col items-center sm:max-w-[70%] w-full md:max-w-[40%] mx-auto overflow-auto`}
      >
        <ThemeProvider>
          <Navbar />
            <main className="flex-1 w-full mt-5">
              {children}
            </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
